name: potube_web
description: Upload-first media to MP3 converter built with Jaspr.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  jaspr: ^0.23.2
  jaspr_router: ^0.8.3

dev_dependencies:
  lints: ^5.0.0
  build_runner: ^2.15.0
  jaspr_builder: ^0.23.2

jaspr:
  mode: server
